import type { InsightPost } from "../types";

// Migrated from the old hardcoded `posts` array in routes/insights.tsx (2026-08-24 SEO/AEO
// pass). Full body + faq added 2026-08-26 — see tvg-marketing-sites-melt-calculator-build
// project doc for the content build log.
export default {
  slug: "settling-internationally-without-logistics-risk",
  kicker: "Operations",
  title: "Settling internationally without taking logistics risk",
  description:
    "FCA, EXW, and DAP in plain English, and how we structure collection so the seller carries no transit exposure.",
  date: "2026-05-09",
  readTime: "5 min read",

  heroDek: "Whatever term sits in the purchase agreement, the metal becomes our responsibility from the point of collection, not the seller’s.",
  chips: ["Incoterms 2020", "Collection", "Risk transfer"],
  body: [
    { type: "p", text: "A purchase agreement for precious metal typically names an Incoterm, most often EXW, FCA, or DAP, and that term fixes the exact point in a shipment where cost and risk pass from seller to buyer. A seller reading that clause for the first time can reasonably wonder whether they are expected to arrange transport, buy insurance, or manage customs themselves for a consignment worth a significant sum. That is not a naive question. A consignment of gold, silver, or platinum group metal in transit is a real asset with real value, and it is reasonable to ask who is answerable for it between the moment it leaves a seller’s premises and the moment it is confirmed received. Under a TVG purchase agreement, the answer is straightforward. We select and manage the collection ourselves, and our contracts are drafted so that a seller’s obligations end at the point of collection, whichever of these terms is used." },
    { type: "h2", id: "what-exw-fca-dap-mean", text: "What EXW, FCA, and DAP mean" },
    { type: "p", text: "EXW, FCA, and DAP are 3 of the 11 Incoterms 2020 rules published by the International Chamber of Commerce, and each one draws the cost-and-risk line at a different stage of a shipment. All three appear regularly on precious metal purchase contracts. Reading a contract without knowing which one applies makes it difficult to judge what, if anything, a seller is expected to do once the metal leaves their premises. The practical difference between the three is where a seller’s responsibility for the goods actually stops, and what the buyer is left to arrange from that point onward." },
    { type: "steps", items: [
      { title: "EXW (Ex Works)", body: "The seller’s only obligation is to make the goods available at a named location, typically their own premises. Cost and risk pass to the buyer at that point, before the goods are even loaded for transport. The buyer arranges and pays for collection, export formalities, carriage, and import." },
      { title: "FCA (Free Carrier)", body: "The seller delivers the goods, cleared for export, to a carrier or party named by the buyer, at an agreed location, which can still be the seller’s own premises. Risk passes to the buyer once that handover happens. The seller keeps responsibility for export clearance, which is one reason FCA is used more often than EXW for cross-border sales." },
      { title: "DAP (Delivered at Place)", body: "The party arranging carriage bears cost and risk for the entire transit to a named destination, not unloaded. Risk passes to the receiving party only once the goods arrive there. Import clearance, duties, and taxes become the receiving party’s responsibility from that point on." }
    ] },
    { type: "h2", id: "why-the-term-matters", text: "Why the named term matters to a seller" },
    { type: "p", text: "It matters because it fixes the exact point at which a seller stops carrying legal and financial exposure for the metal, and that point can fall very early or very late in the journey depending on the term used. Cost tends to follow the same line as risk: whoever is responsible for the metal at a given stage is generally also the party paying to move, insure, and clear it. Under EXW or FCA, the transfer point sits at or close to the seller’s own premises, so a seller’s exposure in transit is already limited by the contract itself. What the term does not settle is who physically organises the carrier, buys the cover, and manages the paperwork between collection and the metal reaching a refiner, and that operational gap is usually where a seller’s practical uncertainty sits, whatever the contract says." },
    { type: "h2", id: "how-we-structure-collection", text: "How we structure collection so the seller carries no transit risk" },
    { type: "p", text: "We select, book, and manage the carrier ourselves, and the consignment moves under insured cover from the point of collection through to arrival at an LBMA-accredited refiner. A seller is never asked to source a freight provider capable of handling precious metal, buy their own transit cover, or manage export or import paperwork. Precious metal is not a category most general freight providers handle routinely, and getting the export classification or licensing wrong can hold a shipment at the border regardless of who is nominally responsible for it. This matches the legal position under EXW or FCA, where risk already passes to us at collection, and it closes the practical gap on top of that: our own people or a carrier we have appointed take physical custody at collection, and the metal is recorded, sealed, and tracked under our own chain-of-custody procedure from that point until it reaches the refiner." },
    { type: "callout", label: "What this means", text: "Once collection has taken place, the metal is TVG’s legal and physical responsibility, not the seller’s. There is nothing further for the seller to arrange, insure, or track." },
    { type: "p", text: "This structure is documented, not just practised. Collection is confirmed in writing, the carrier’s handling of the consignment is recorded, and the chain of custody from collection to refiner forms part of the transaction record available to the seller. A seller does not need to take our word for where the metal is or who is responsible for it at any given stage, and does not need to wait for a safe arrival at destination before payment is triggered. That combination of a signed contract, insured and managed transit, and settlement tied to confirmed collection rather than final delivery is what separates a documented counterparty from a cash buyer who takes the metal and disappears." }
  ],
  faq: [
    { q: "Do I need to arrange my own transport or insurance for the shipment?", a: "No, not under a TVG purchase agreement. TVG selects, books, and insures the carrier for every collection, whichever Incoterm the contract uses. A seller is not expected to source a freight provider, buy transit cover, or manage the logistics leg." },
    { q: "Who chooses the carrier that collects the metal?", a: "TVG does. We work with carriers experienced in handling precious metal and appoint them directly, rather than asking a seller to find and vet a freight provider capable of moving a high-value, tightly regulated consignment." },
    { q: "Does the Incoterm affect when I get paid?", a: "Not in the way it might seem to. Settlement under a TVG purchase agreement is generally tied to confirmed collection, evidenced by a collection receipt or transport document, rather than to the metal’s arrival at its final destination. A delay in transit after collection does not typically delay payment to the seller." },
    { q: "What happens if a shipment is delayed or held at customs after collection?", a: "That becomes TVG’s issue to resolve. Once the metal has been collected, TVG is responsible for the consignment in transit, including managing any delay, customs query, or documentation issue that arises before it reaches the refiner." },
    { q: "Why does a purchase contract specify EXW or FCA rather than simply stating that TVG will handle everything?", a: "Because the Incoterm is what makes the risk transfer and each party’s obligations enforceable in writing, not just a matter of practice. The specific term used in a given contract usually reflects the seller’s own export capability and the collection location. Which term is named does not change TVG’s approach: TVG funds, arranges, and manages the collection and onward transit in every case." }
  ],
} satisfies InsightPost;
