import type { InsightPost } from "../types";

// Migrated from the old hardcoded `posts` array in routes/insights.tsx (2026-08-24 SEO/AEO
// pass). Full body + faq added 2026-08-26 — see tvg-marketing-sites-melt-calculator-build
// project doc for the content build log.
export default {
  slug: "source-of-goods-documented",
  kicker: "Compliance",
  title: "Source of goods: what 'documented' actually means",
  description:
    "A short walk through the evidence pack we ask for, why each document matters, and how to put it together without slowing the trade.",
  date: "2026-05-28",
  readTime: "8 min read",

  heroDek: "The paperwork a refiner needs before metal changes hands, and how to have it ready before we ask for it.",
  chips: ["Provenance", "KYC", "Chain of custody"],
  body: [
    { type: "p", text: "Documented source of goods means the seller can show, in writing, how the material came to be theirs and that they hold clear authority to sell it. It is what we ask for before pricing any lot of gold, silver, or platinum group metal. Behind that one phrase sit the origin of the metal, an unbroken record of custody from there to the refiner, and confidence that the seller is legally entitled to sell it. Get all of that right and a trade moves at the speed pricing and logistics allow. Get any part of it wrong, or missing, and everything else waits on it." },
    { type: "h2", text: "Why does a documented source of goods matter?" },
    { type: "p", text: "Refiners and credible buyers ask for a documented source because they cannot process material they cannot account for, and the buyers who take refined metal from them afterward cannot either. LBMA-accredited refiners operate under their own responsible sourcing obligations, closely aligned with LBMA Responsible Gold and Silver Guidance, and what they accept from us has to hold up against what they in turn have to show their own regulators and clients. A complete record is not TVG asking a seller to clear an unnecessary hurdle. It is TVG passing the same standard forward, from the seller’s premises to the refined bar." },
    { type: "p", text: "How closely we examine a source is proportionate to risk, not a fixed hurdle applied the same way to every seller. A corporate treasury divesting a legacy inventory programme in a well-established jurisdiction sits at a different risk level than material moving through a higher-risk transit route, and the depth of review reflects that difference. This is the same risk-based approach the wider industry works to, consistent with internationally recognised due diligence guidance for precious metal supply chains. Most sellers clear the standard evidence pack without anything further being asked. Where something does not sit right, we ask before we buy, not after." },
    { type: "h2", text: "What counts as an auditable chain of custody?" },
    { type: "p", text: "An auditable chain of custody is a record that follows the material from the seller’s premises to the refiner without a gap at any step. Each lot is given its own reference, a weight and description recorded at the point of collection, transport and customs documentation for the leg in between, and a dated record of when it reached the refiner and what the assay confirmed. None of this is exotic paperwork. It is close to what any commercial goods movement already requires, applied with more consistency because the material is precious metal and every party downstream is checking it. None of it requires the seller to run specialised logistics or compliance systems of their own. We assign the lot reference, arrange the collection and transport paperwork, and share the completed record with the seller once the trade settles, so the audit trail exists without the seller having to build it." },
    { type: "p", text: "The part sellers tend to underestimate is not any single document. It is consistency across all of them. A lot described with one weight on the collection note, a different value on the invoice, and a third address on the transport paperwork draws more scrutiny than a straightforward gap the seller has already flagged. We reconcile our own paperwork, document against document, before anything is presented to a refiner, for exactly this reason." },
    { type: "h2", text: "What does the evidence pack contain?" },
    { type: "p", text: "The evidence pack covers who authorised the sale, how the seller came to hold the material, who the seller actually is, and, where one exists, what the material was previously valued or insured at. We ask a seller to assemble it alongside pricing and logistics, not as a prerequisite that has to close before anything else can start. None of these is unusual for a corporate counterparty to produce. What varies is which parts a given seller already has to hand, and which need a short conversation to establish." },
    { type: "steps", items: [
      { title: "Authorisation to sell", body: "A board resolution, a signed instruction from a director or equivalent senior officer, or an insolvency practitioner’s own instrument of appointment and authority to realise assets. We need to know the person signing the contract has the standing to bind the seller, because a purchase agreement signed by the wrong person is not one a court, an auditor, or a refiner will treat as valid. This does not need to be an elaborate document. It needs to be genuine, current, and signed by someone with the authority the seller’s own constitution actually gives them." },
      { title: "Proof of ownership or acquisition", body: "An asset register entry, a purchase or acquisition record, an administration asset schedule, or, for an industrial seller, production records showing the material is process byproduct rather than something acquired from a third party. This is the document that answers the question that actually matters: whether the seller has the right to sell this material. We ask what form of proof applies to the seller’s specific situation, rather than requesting a fixed template that assumes every seller acquired the material the same way." },
      { title: "Corporate KYC", body: "Incorporation documents, registered address, and identification of beneficial owners holding a significant stake in the business, screened the way any regulated counterparty screens a new relationship. Refiners and the banks that settle the wire sit inside the same regulatory perimeter TVG does, and neither can transact with a counterparty whose ownership is not established. This is standard onboarding, not something specific to precious metals, and it is usually the fastest part of the pack to close when a seller’s own corporate records are already in order." },
      { title: "Prior valuation or insurance schedule, where one exists", body: "Not a requirement to trade. Where a valuation or an insurance schedule already covers the material, it corroborates the description the seller has given and can shorten the questions we need to ask before pricing at LBMA spot." }
    ] },
    { type: "h2", text: "Why does proof of ownership look different for every seller?" },
    { type: "p", text: "Proof of ownership looks different for every seller because it depends on how the material came to be held, not on a single template document. A corporate treasury holding legacy service award stock usually has an asset register entry, even if the pins themselves have sat at historic cost, or off the books entirely, for years. An insolvency practitioner works from the asset schedule already filed as part of the administration. An industrial manufacturer with filings, grinding sludge, or spent catalyst material points to its own production records, which show the metal accumulating as a byproduct of a process the company already runs, not as something bought in from elsewhere. A jeweller working from trade-ins and old stock typically has purchase or valuation records from its own trading history. We ask for whichever of these genuinely applies, not all of them at once." },
    { type: "callout", label: "When the paper trail is incomplete", text: "Legacy inventory rarely comes with a complete file. A programme that ran for 20 years and was never actively managed will usually have gaps, and that is treated as a starting point for the conversation, not a reason to decline it. We identify what is genuinely missing early, tell the seller what will actually satisfy the requirement, and work from what does exist rather than insisting on a record that was never going to survive that long in the first place." },
    { type: "h2", text: "How does TVG run this without slowing the trade?" },
    { type: "p", text: "We collect the evidence pack in parallel with pricing and logistics, not as a separate stage that has to finish before the rest of the deal can move. The moment a seller describes what they are holding, we open the documentation conversation alongside the weighing, assay, and pricing work, so the two tracks land at roughly the same time instead of one waiting on the other. A single point of contact manages the document request, checks it against what the seller’s own structure actually requires rather than a generic list, and confirms early whether a substitute will do." },
    { type: "p", text: "None of it is asked for out of caution alone. Each item in the evidence pack maps to a specific question a refiner, a bank, or a regulator will eventually ask, and we would rather answer it once, upfront, than reopen it at the point of settlement. A seller who can show authorisation, ownership, KYC, and, where relevant, a prior valuation, is a seller we can price, contract, and settle without a pause to go back and ask. The paperwork is what lets the wire go out on schedule. That is the same discipline behind the wider proposition: compliant acquisition, global settlement, and no logistics risk sitting with the seller at any point in the process." }
  ],
  faq: [
    { q: "What counts as valid authorisation if there is no formal board resolution?", a: "It depends on the seller’s own legal structure. A limited company typically provides a board resolution or a signed instruction from a director with authority to bind the company. An insolvency practitioner provides their own instrument of appointment. A sole trader or partnership provides a signed instruction from the owner or partners. We confirm the minimum accepted form for a given seller’s structure at the start of the conversation, rather than asking for a fixed template that does not fit every entity type." },
    { q: "What if the material was acquired decades ago and there is no purchase record left?", a: "This is common with legacy inventory, and it is treated as a starting point rather than a blocker. An asset register entry, even one carrying the material at historic cost or showing it was never capitalised at all, is usually enough to begin. We work from what genuinely exists and confirm the rest through the KYC and authorisation steps, rather than insisting on a purchase record that was never going to survive that long." },
    { q: "Is an existing valuation required before TVG will make an offer?", a: "Not as a precondition. We price the material at LBMA spot based on our own weighing and assay, so a prior valuation is not required to trade. Where one exists, alongside an insurance schedule, it corroborates the seller’s own description and can shorten the questions asked before contract, but its absence does not stop the process." },
    { q: "How long does the documentation review add to the transaction timeline?", a: "In most cases, none. We collect the evidence pack in parallel with pricing, weighing, and logistics, starting from the first conversation about what the seller is holding, so by the time commercial terms are agreed the documentation is usually settled alongside them rather than after." },
    { q: "What happens if a requested document is missing?", a: "We identify the gap early and state plainly whether it is a genuine blocker or something a substitute document can satisfy. Most gaps fall into the second category. The aim is to establish what is actually required for the seller’s specific situation, not to work through a generic checklist regardless of relevance." }
  ],
} satisfies InsightPost;
