import type { InsightPost } from "../types";

// Migrated from the old hardcoded `posts` array in routes/insights.tsx (2026-08-24 SEO/AEO
// pass). Full body + faq added 2026-08-26 — see tvg-marketing-sites-melt-calculator-build
// project doc for the content build log. Deliberately avoids citing any specific historical
// price level for any metal — see that doc for why.
export default {
  slug: "why-corporates-sit-on-legacy-metal",
  kicker: "Market note",
  title: "Why corporates sit on legacy metal — and what unlocks it",
  description:
    "Award programmes, retired product lines, and discontinued inventory build up faster than treasury teams realise. A look at how finance functions are clearing the position.",
  date: "2026-06-12",
  readTime: "6 min read",

  heroDek: "Most legacy metal is not lost, only unpriced and unowned until someone does the work of establishing what it is worth.",
  chips: ["Corporate treasury", "Legacy inventory", "Balance sheet cleanup"],
  body: [
    { type: "p", text: "Corporates end up holding gold, silver and platinum group metal for years past the point it stopped being useful to them because nobody inside the business was ever assigned the job of selling it. The metal itself is real, sitting in a warehouse, a locked cabinet or a subsidiary’s storeroom. What is missing is the paperwork trail, the pricing knowledge and the sense of ownership that would turn it back into cash. That gap, not the value of the material, is what keeps a position sitting untouched long after the programme or product line that created it has ended. None of this requires negligence. It is simply what happens once a programme winds down, a product line closes, or a company changes hands, and nobody is left holding specific responsibility for the metal it leaves behind." },
    { type: "h2", id: "where-it-comes-from", text: "Where does legacy precious metal inventory come from?" },
    { type: "p", text: "4 situations account for most of it: long-running service or incentive award programmes that were never formally wound down, discontinued product lines whose remaining stock was never reallocated, mergers and acquisitions that left inventory on the balance sheet without anyone inheriting responsibility for it, and simple organisational drift once the person who understood the material moves on." },
    { type: "list", items: [
      "Service and incentive award programmes. A long-running scheme, gold or silver service pins among them, generates a running stock of metal that was designed to be distributed, not sold, and stops being actively tracked the moment the programme itself winds down.",
      "Discontinued product lines. When a product using precious metal components is retired, remaining raw material, components or finished units are typically moved into storage rather than actioned, with nothing on the balance sheet prompting anyone to revisit them later.",
      "Mergers and acquisitions. An inventory schedule transfers with a deal, but the operational relationship behind it, if one ever existed, usually does not. The incoming finance team inherits the asset without inheriting anyone who knows what it is worth or how to sell it.",
      "Organisational drift. Roles change and people leave, and the informal knowledge of what a stockroom, a safe or a subsidiary site actually contains goes with them, leaving a line item with no one holding an active reason to revisit it."
    ] },
    { type: "h2", id: "why-it-stays", text: "Why does it stay on the books instead of getting sold?" },
    { type: "p", text: "It stays there because 3 basic questions go unanswered inside the business. Nobody is confident what the material is worth today, since it typically sits at historic cost, at a nominal value, or is not recorded as a distinct line on the balance sheet at all. That gap matters more than it looks: metal held for years without being revalued at a current price is often worth meaningfully more than its book value or its off-books status suggests, which turns simple uncertainty into a real cost, not a neutral position. And nobody inside the business has an existing relationship with a refinery or a trading counterparty capable of actually buying the material in a documented, compliant way, so even a confident valuation has nowhere obvious to go." },
    { type: "p", text: "The third question is about risk, not value. Selling precious metal outside a normal supply chain means choosing a buyer, and choosing the wrong one, an unverified cash buyer, an intermediary nobody has checked, a counterparty finance or legal never signed off on, creates personal and organisational exposure that is easy to avoid simply by not acting. Nobody wants to be the person who approved that buyer if it later becomes a problem, so the lowest-risk internal decision, almost always, is to leave the position exactly where it is." },
    { type: "p", text: "The economics of the position reinforce the inertia. The value involved is frequently too small to justify a dedicated internal project, a formal procurement process, or meaningful legal review time, but too large to write off or quietly forget about. That combination, real money attached to a task nobody has been formally asked to complete, is what allows a line item to sit untouched for years without anyone treating it as a live problem. It is rarely a decision. It is closer to an absence of one." },
    { type: "h2", id: "what-moves-it", text: "What actually gets a dormant position moving?" },
    { type: "p", text: "In practice, 3 events reliably move a dormant position. A credible counterparty approaches the business directly, does the valuation work itself, and puts a specific, defensible number in front of someone who did not have to go looking for one. An audit, a divestment or an acquisition forces a genuine line-by-line review of the balance sheet, surfacing entries that have not been questioned in years. Or a newly appointed finance director, treasurer or head of procurement reviews the accounts, notices an unfamiliar entry, and asks what it actually is and why it is still there. None of these require the business to run a project of its own. Each one simply replaces a vague, ongoing sense that something should be dealt with, with a specific number, a specific deadline or a specific question that someone is now accountable for answering." },
    { type: "h2", id: "tvg-approach", text: "What does TVG’s audit-and-price approach solve?" },
    { type: "p", text: "It solves the 2 questions that were never answered internally: what the material is actually worth, and who is safe to sell it to. TVG audits the inventory on site or from documentation supplied by the business, prices it against LBMA benchmark rates rather than a discounted cash offer, and puts that valuation into a signed purchase contract with the seller’s own legal team involved throughout. Collection, export compliance and settlement are handled end to end, so the finance function is not left managing logistics or chain of custody on top of a transaction it never had the internal expertise to run alone. That applies equally to inventory left behind by a merger or an acquisition, spread across several subsidiaries and jurisdictions, and to a single site holding the remaining stock of one long-closed programme. Once that first line item is priced, documented and sold, it stops being a question the business has to keep not answering." }
  ],
  faq: [
    { q: "How do we find out what our legacy precious metal inventory is actually worth?", a: "The most reliable starting point is a physical or documentary audit measured against current LBMA benchmark prices, not the historic cost the material may already carry on the books. TVG carries out this audit directly, on site or from photographs, weights and specification sheets supplied by the business, and returns a fair market valuation before any commitment is required." },
    { q: "Does the inventory need to be in one location before it can be sold?", a: "No. Inventory split across subsidiaries, sites or jurisdictions can typically be consolidated into a single transaction, or handled as separate agreements per entity, depending on how the business is structured. The audit stage is where that structure gets mapped and a workable settlement approach is agreed." },
    { q: "What if the material was never recorded as an asset, or was written down to a nominal value?", a: "That is common, not a barrier. A gap between book value and actual market value is one of the main reasons this kind of inventory goes unaddressed for years, and an independent valuation at current benchmark pricing resolves it, regardless of how the asset was originally recorded." },
    { q: "Who typically needs to be involved internally before a sale like this can happen?", a: "That depends on the business, but a purchase agreement of this kind usually involves finance or treasury, legal, and whoever holds delegated authority for asset disposals above a given threshold. TVG signs a purchase contract directly with the seller’s own legal team, so the business retains full control of that approval process." },
    { q: "How is payment actually settled once a valuation is agreed?", a: "Settlement follows collection and, where relevant, assay confirmation, with payment wired directly to the seller under the terms of the signed agreement. There is no cash handover and no informal exchange. Every step, from valuation through to final payment, is documented." }
  ],
} satisfies InsightPost;
