/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AmlPolicyRouteImport } from './routes/aml-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesCorporateLiquidationRouteImport } from './routes/guides.corporate-liquidation'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AmlPolicyRoute = AmlPolicyRouteImport.update({
  id: '/aml-policy',
  path: '/aml-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesCorporateLiquidationRoute =
  GuidesCorporateLiquidationRouteImport.update({
    id: '/guides/corporate-liquidation',
    path: '/guides/corporate-liquidation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aml-policy': typeof AmlPolicyRoute
  '/compliance': typeof ComplianceRoute
  '/insights': typeof InsightsRoute
  '/guides/corporate-liquidation': typeof GuidesCorporateLiquidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aml-policy': typeof AmlPolicyRoute
  '/compliance': typeof ComplianceRoute
  '/insights': typeof InsightsRoute
  '/guides/corporate-liquidation': typeof GuidesCorporateLiquidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aml-policy': typeof AmlPolicyRoute
  '/compliance': typeof ComplianceRoute
  '/insights': typeof InsightsRoute
  '/guides/corporate-liquidation': typeof GuidesCorporateLiquidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aml-policy'
    | '/compliance'
    | '/insights'
    | '/guides/corporate-liquidation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aml-policy'
    | '/compliance'
    | '/insights'
    | '/guides/corporate-liquidation'
  id:
    | '__root__'
    | '/'
    | '/aml-policy'
    | '/compliance'
    | '/insights'
    | '/guides/corporate-liquidation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmlPolicyRoute: typeof AmlPolicyRoute
  ComplianceRoute: typeof ComplianceRoute
  InsightsRoute: typeof InsightsRoute
  GuidesCorporateLiquidationRoute: typeof GuidesCorporateLiquidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aml-policy': {
      id: '/aml-policy'
      path: '/aml-policy'
      fullPath: '/aml-policy'
      preLoaderRoute: typeof AmlPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/corporate-liquidation': {
      id: '/guides/corporate-liquidation'
      path: '/guides/corporate-liquidation'
      fullPath: '/guides/corporate-liquidation'
      preLoaderRoute: typeof GuidesCorporateLiquidationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmlPolicyRoute: AmlPolicyRoute,
  ComplianceRoute: ComplianceRoute,
  InsightsRoute: InsightsRoute,
  GuidesCorporateLiquidationRoute: GuidesCorporateLiquidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
